name: Unassign issue on move to Backlog (Projects Beta)

on:
  projects_v2_item:
    types:
      - edited

jobs:
  unassign-card:
    runs-on: ubuntu-latest
    steps:
      - name: Unassign issue when moved to Backlog (Projects Beta)
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fieldName = "Status"; // Change this to your status field name
            const backlogValue = "Backlog"; // Change this to your backlog value
            
            const itemId = context.payload.projects_v2_item.id;
            const projectId = context.payload.projects_v2_item.project_node_id;

            // Query Project item fields
            const result = await github.graphql(`
              query($projectId: ID!, $itemId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    item(id: $itemId) {
                      id
                      fieldValues(first: 20) {
                        nodes {
                          value
                          projectField {
                            name
                          }
                        }
                      }
                      content {
                        ... on Issue {
                          id
                          number
                          assignees(first: 10) {
                            nodes {
                              login
                            }
                          }
                          repository {
                            name
                            owner { login }
                          }
                        }
                        ... on PullRequest {
                          id
                          number
                          assignees(first: 10) {
                            nodes {
                              login
                            }
                          }
                          repository {
                            name
                            owner { login }
                          }
                        }
                      }
                    }
                  }
                }
              }
            `, {
              projectId,
              itemId
            });

            const item = result.node.item;
            const statusField = item.fieldValues.nodes.find(field => field.projectField.name === fieldName);

            if (statusField && statusField.value === backlogValue) {
              const content = item.content;
              if (content) {
                const assignees = content.assignees.nodes.map(a => a.login);
                if (assignees.length > 0) {
                  await github.rest.issues.removeAssignees({
                    owner: content.repository.owner.login,
                    repo: content.repository.name,
                    issue_number: content.number,
                    assignees: assignees
                  });
                  console.log(`Unassigned users ${assignees.join(', ')} from issue #${content.number}.`);
                } else {
                  console.log(`Issue #${content.number} has no assignees to remove.`);
                }
              } else {
                console.log('Project item is not an issue or pull request.');
              }
            } else {
              console.log('Project item status is not Backlog.');
            }